# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Ambassador' do
pod 'libPusher', '~> 1.6'
pod 'FMDB'
end

target 'AmbassadorTests' do

end

target 'AmbassadorResources' do

end

target 'TestApplication' do

end

target 'TestApplicationTests' do

end

